- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: true
    tags:
    - node
    - zsh
  tasks:
  - import_tasks: tasks/zhs.yml
  - import_tasks: tasks/node.yml
  - import_tasks: tasks/nginx.yml
  - import_tasks: tasks/pm2.yml





