- hosts: localhost
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: true
    tags:
    - node
    - zsh
  tasks:
  - include: tasks/zsh.yml
  - include: tasks/node.yml
  - include: tasks/nginx.yml
  - include: tasks/pm2.yml

  # tasks:
  # - import_tasks: tasks/zsh.yml
  # - import_tasks: tasks/node.yml
  # - import_tasks: tasks/nginx.yml
  # - import_tasks: tasks/pm2.yml





