- hosts: all
  become: true
  pre_tasks:
  - name: Update cache
    apt:
      update_cache: true
    tags:
    - node
    - zsh
  tasks:
  - include_tasks: tasks/zhs.yml
  - include_tasks: tasks/node.yml
  - include_tasks: tasks/docker.yml
  - include_tasks: tasks/nginx.yml
  - include_tasks: tasks/pm2.yml





